Fix Upserting temporary volume
stashed/stash pull request #1498
Opened 2022-12-27 12:41 UTC by hmsayem

Signed-off-by: hmsayem <hmsayem@appscode.com>

2023-01-02 10:00 UTC, piyush1146115 approved these changes

2023-01-03 05:38 UTC, hossainemruz requested changes

2023-01-03 05:38 UTC, hossainemruz commented on pkg/cmds/server/options.go
> +		ScratchDir:     "/stash-tmp",
Use `restic.DefaultScratchDir`

2023-01-03 05:38 UTC, hossainemruz commented on pkg/util/crds.go
> +				"--scratch-dir=/stash-tmp",
Use `fmt.Sprintf("%s",restic.DefaultScratchDir)`

2023-01-03 05:38 UTC, hossainemruz commented on pkg/util/crds.go
> +				"--scratch-dir=/stash-tmp",
Use `fmt.Sprintf("%s",restic.DefaultScratchDir)`

2023-01-03 05:38 UTC, hossainemruz commented on pkg/util/crds.go
> +				"--scratch-dir=/stash-tmp",
Use `fmt.Sprintf("%s",restic.DefaultScratchDir)`

2023-01-03 05:38 UTC, hossainemruz commented on pkg/util/crds.go
> +							Value: "/stash-tmp/output",
Use `fmt.Sprintf("%s/output",restic.DefaultScratchDir)`

2023-01-03 05:38 UTC, hossainemruz commented on pkg/util/crds.go
> +							Value: "/stash-tmp/output",
Use `fmt.Sprintf("%s/output",restic.DefaultScratchDir)`

2023-01-03 05:38 UTC, hossainemruz commented on pkg/util/crds.go
> +							Value: "/stash-tmp/output",
Use `fmt.Sprintf("%s/output",restic.DefaultScratchDir)`

2023-01-03 05:38 UTC, hossainemruz commented on pkg/util/crds.go
> +							Value: "/stash-tmp/output",
Use `fmt.Sprintf("%s/output",restic.DefaultScratchDir)`

2023-01-03 06:43 UTC, hossainemruz approved these changes

2023-01-03 07:01 UTC, hossainemruz approved these changes

2023-01-03 07:02 UTC, merged